kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeserve
      version: v1
  template:
    metadata:
      name: deploy-blue
      labels:
        app: kubeserve
        version: v1
    spec:
      containers:
       - name: app
         image: leaddevops/kubeserve:v1
        
---
kind: Service
apiVersion: v1
metadata:
   name: service-blue
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector: 
    app: kubeserve
    version: v1
